/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export class FileConstants {
  static readonly FULL_PERCENT: string = '100%';
  static readonly GOOD_TYPE: string[] = ['Mate60', 'Mate60pro', 'Mate40', 'Mate40pro'];
  static readonly MATE60: string = 'Mate60';
  static readonly MATE60PRO: string = 'Mate60pro';
  static readonly MATE40: string = 'Mate40';
  static readonly MATE40PRO: string = 'Mate40pro';
  static readonly FONT_WEIGHT_400: number = 400;
  static readonly FONT_WEIGHT_500: number = 500;
  static readonly FONT_WEIGHT_700: number = 700;
  static readonly LINE_HEIGHT_21: number = 21;
  static readonly LINE_HEIGHT_40: number = 40;
  static readonly BUTTON_BACKGROUND_COLOR: number = 0x0c000000;
  static readonly COMPARE_PRICE1: number = 5000;
  static readonly COMPARE_PRICE2: number = -5000;
  static readonly PERCENT_30: string = '30%';
  static readonly PERCENT_23: string = '23%';
  static readonly PERCENT_8: string = '8%';
  static readonly PERCENT_87: string = '87%';
  static readonly PERCENT_2: string = '2%';
  static readonly PERCENT_95: string = '95%';
  static readonly PERCENT_35: string = '35%';
  static readonly PERCENT_7: string = '7%';
  static readonly PERCENT_13: string = '13%';
  static readonly PERCENT_91: string = '91%';
  static readonly PERCENT_11: string = '11%';
  static readonly PERCENT_6: string = '6%';
  static readonly PERCENT_3: string = '3%';
  static readonly PERCENT_9: string = '9%';
}