/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class ImageCropConstants {
  static readonly THREE_FOUR: number = 4 / 3;
  static readonly NINE_SIXTH: number = 16 / 9;
  static readonly ONE_ONE: number = 1;
  static readonly ROW_SPACE: number = 24;
  static readonly SHOW_TOAST_DURATION: number = 2000;
  static readonly LIST_HEIGHT: number = 72;
  static readonly SAVE_LENGTH: number = 32;
  static readonly LIST_ITEM_LENGTH: number = 30;
  static readonly PACKING_QUALITY_FULL: number = 100;
  static readonly PACKING_QUALITY_PERCENT_THIRTY: number = 30;
  static readonly RAWFILE_PIC_PATH: string = "depthCopy.png";
  static readonly FULL_SCREEN: string = "100%";
  static readonly PERCENT_SEVENTY: string = "70%";
  static readonly PERCENT_TWENTY_FIVE: string = "25%";
  static readonly IMAGE_FORMAT: string = ".jpg";
  static readonly PACKING_FORMAT: string = "image/jpeg";
  static readonly URI_HEAD: string = "file:/";
}