/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class CommonConstants {

  /**
   * Space between components.
   */
  static readonly SPACE: string = '20vp';

  /**
   * Content width.
   */
  static readonly CONTENT_WIDTH: string = '18%';

  /**
   * Content row width.
   */
  static readonly CONTENT_ROW_WIDTH: string = '75%';

  /**
   * Scroll width.
   */
  static readonly SCROLL_WIDTH: string = '115%';

  /**
   * Layout weight.
   */
  static readonly LAYOUT_WEIGHT: number = 1;

  /**
   * Loop count.
   */
  static readonly LOOP_COUNT: number = 3;

  /**
   * Max data length.
   */
  static readonly MAX_DATA_LENGTH: number = 18;
}