/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class Constants {
  /**
   * Full percent.
   */
  static readonly FULL_PERCENT: string = '100%';

  /**
   * Eighty percent.
   */
  static readonly EIGHTY_PERCENT: string = '80%';

  /**
   * Seventy-six percent.
   */
  static readonly SEVENTY_SIX_PERCENT: string = '76%';

  /**
   * Fifty percent.
   */
  static readonly FIFTY_PERCENT: string = '50%';

  /**
   * Sets the style of Progress.
   */
  static readonly PROGRESS_TOTAL: number = 100;

  /**
   * Increase Down Load Progress.
   */
  static readonly DOWN_LOAD_PROGRESS: number = 20;

  /**
   * Max Down Load Progress.
   */
  static readonly MAX_DOWN_PROGRESS: number = 100;

  /**
   * Delay Time.
   */
  static readonly DELAY_TIME: number = 1000;

  /**
   * Long Video Info.
   */
  static readonly VIDEO_INFO_LONG: number = 120;
  
  /**
   * Timestamp Interval.
   */
  static readonly TIMESTAMP_INTERVAL: number = 300;
}