/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class CommonConstants {
  /**
   * List space.
   */
  static readonly LIST_SPACE: number = 5;

  /**
   * List width.
   */
  static readonly LIST_WIDTH: string = '95%';

  /**
   * Full width.
   */
  static readonly FULL_WIDTH: string = '100%';

  /**
   * Full height.
   */
  static readonly FULL_HEIGHT: string = '100%';

  /**
   * Button margin.
   */
  static readonly BUTTON_MARGIN: string = '25%';

  /**
   * Image width and grid width.
   */
  static readonly IMAGE_WIDTH: string = '90%';

  /**
   * Picture item number.
   */
  static readonly PICTURE_ITEM_NUMBER: number = 9;

  /**
   * Number of copies of the picture cut horizontally and vertically.
   */
  static readonly SPLIT_COUNT: number = 3;

  /**
   * Game duration.
   */
  static readonly GAME_TIME: number = 300;

  /**
   * TAG.
   */
  static readonly TAG: string = 'Index';

  /**
   * Loop number.
   */
  static readonly LOOP: number = 7;

  /**
   * Grid count.
   */
  static readonly GRID_COUNT: number = 12;

  /**
   * Time number.
   */
  static readonly TIME_NUMBER: number = 1000;

  /**
   * Image show.
   */
  static readonly IMAGE_SHOW: string = 'imageShow';

  /**
   * Time.
   */
  static readonly TIME: number = 200;

  /**
   * Grid image width.
   */
  static readonly GRID_IMAGE_WIDTH: string = '99%';

  /**
   * Seconds.
   */
  static readonly SECOND: number = 60;

  /**
   * Margin.
   */
  static readonly MARGIN: number = 5;

  /**
   * Margin 1 percent.
   */
  static readonly PERCENT: string = '1%';

  /**
   * Zero.
   */
  static readonly ZERO: number = 0;

  /**
   * ONE.
   */
  static readonly ONE: number = 1;

  /**
   * Five.
   */
  static readonly FIVE: number = 5;

  /**
   * Ten.
   */
  static readonly TEN: number = 10;

  /**
   * String zero.
   */
  static readonly STRING_ZERO: string = '0';

  /**
   * Time.
   */
  static readonly TIME_STRING: string = 'time';

  /**
   * Cancel Button.
   */
  static readonly CANCEL_BUTTON: string = 'cancel';

  /**
   * Confirm Button.
   */
  static readonly CONFIRM_BUTTON: string = 'confirm';

  /**
   * Start Button.
   */
  static readonly START_BUTTON: string = 'start';

  /**
   * Restart Button.
   */
  static readonly RESTART_BUTTON: string = 'restart';

  /**
   * The radio value.
   */
  static readonly RADIO_VALUE: string = 'Radio3';

  /**
   * The radio group.
   */
  static readonly RADIO_GROUP: string = 'radioGroup';

  /**
   * The image grid.
   */
  static readonly IMAGE_GRID: string = 'imageGrid';

  /**
   * The columnsTemplate.
   */
  static readonly COLUMN_TEMPLATE: string = '1fr 1fr 1fr';
}