/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Public constants.
 */
export class Constants {
  /**
   * Full percent.
   */
  static readonly FULL_PERCENT: string = '100%';

  /**
   * Byte Unit.
   */
  static readonly BYTE_UNIT: string = ' Byte';

  /**
   * File Path Name.
   */
  static readonly FILE_PATH_NAME: string = '/test.txt';

  /**
   * Write Content.
   */
  static readonly WRITE_CONTENT: string = '/test.txt';

  /**
   * Apply the spatial statistics page.
   */
  static readonly APP_SPACE_PAGE: string = 'AppSpacePage';

  /**
   * File System Storage Statistics page.
   */
  static readonly FILE_SPACE_PAGE: string = 'FileSpacePage';
}