/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class FormConstants {
  /**
   * List width.
   */
  static readonly LIST_WIDTH: string = '90%';

  /**
   * List height.
   */
  static readonly LIST_HEIGHT: string = '60%';

  /**
   * Full width.
   */
  static readonly FULL_WIDTH: string = '100%';

  /**
   * Text width.
   */
  static readonly TEXT_WIDTH: string = '80%';
}