/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class CommonConstants {

  /**
   * Month.
   */
  static readonly MONTHS = 12;

  /**
   * January.
   */
  static readonly JANUARY = 1;

  /**
   * A week.
   */
  static readonly WEEK_NUMBER = 7;

  /**
   * Month number.
   */
  static readonly MONTH_NUMBER = 35;

  /**
   * Small grid height.
   */
  static readonly GRID_HEIGHT_L = 360;

  /**
   * Large grid height.
   */
  static readonly GRID_HEIGHT_M = 300;

  /**
   * Outside margin.
   */
  static readonly ELEMENTS_MARGIN = 12;

  /**
   * One hundred percent.
   */
  static readonly ONE_HUNDRED_PERCENT: string = '100%';

  /**
   * One hundred eleven percent.
   */
  static readonly ONE_HUNDRED_ELEVEN_PERCENT: string = '111%';

  /**
   * Ninety two percent.
   */
  static readonly NINETY_PERCENT: string = '90%';

  /**
   * Ninety two percent.
   */
  static readonly NINETY_TWO_PERCENT: string = '92%';

  /**
   * Ninety five percent.
   */
  static readonly NINETY_FIVE_PERCENT: string = '95%';

  /**
   * Eighty five percent.
   */
  static readonly EIGHTY_FIVE_PERCENT: string = '85%';

  /**
   * Thirty percent.
   */
  static readonly THIRTY_PERCENT: string = '30%';

  /**
   * Forty percent.
   */
  static readonly FORTY_PERCENT: string = '40%';

  /**
   * Seventy-five percent.
   */
  static readonly SEVENTY_FIVE_PERCENT: string = '75%';

  /**
   * Rotation angle.
   */
  static readonly ANGLE: number = 45;

  /**
   * Line Spacing.
   */
  static readonly SPACE: number = 15;

  /**
   * Moving distance.
   */
  static readonly TRANSLATE: number = 1000;

  /**
   * Zero six.
   */
  static readonly ZERO_SIX: number = 0.6;

  /**
   * Zero eight.
   */
  static readonly ZERO_EIGHT: number = 0.8;

  /**
   * Duration.
   */
  static readonly DURATION: number = 1200;

  /**
   * Delay.
   */
  static readonly DELAY: number = 500;

  /**
   * GridCount.
   */
  static readonly GRID_COUNT: number = 2;

  /**
   * Zero.
   */
  static readonly ZERO: number = 0;

  /**
   * Four
   */
  static readonly FOUR: number = 4;

  /**
   * Eight.
   */
  static readonly EIGHT: number = 8;

  /**
   * Twelves.
   */
  static readonly TWELVES: number = 12;

  /**
   * Space.
   */
  static readonly SPACE_ONE: number = 20;

  /**
   * Element margin large.
   */
  static readonly ELEMENTS_MARGIN_L: number = 24;

  /**
   * Element margin small.
   */
  static readonly ELEMENTS_MARGIN_M: number = 8;

  /**
   * 0.0.
   */
  static readonly ZERO_ZERO: number = 0.0;

  /**
   * 0.3.
   */
  static readonly ZERO_Three: number = 0.3;

  /**
   * 1.0.
   */
  static readonly ONE_ZERO: number = 1.0;

  /**
   * Saturday.
   */
  static readonly SATURDAY: string = '六';

  /**
   * Sunday.
   */
  static readonly SUNDAY: string = '日';

  /**
   * Seven grid.
   */
  static readonly GRID_SEVEN: string = '1fr 1fr 1fr 1fr 1fr 1fr 1fr';

  /**
   * Six grid.
   */
  static readonly GRID_SIX: string = '1fr 1fr 1fr 1fr 1fr 1fr';

  /**
   * Five grid.
   */
  static readonly GRID_FIVE: string = '1fr 1fr 1fr 1fr 1fr';
}