/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Public constants.
 */
export class CommonConstants {
  /**
   * Percentage max.
   */
  static readonly PERCENTAGE_MAX: string = '100%';
  /**
   * Text input width.
   */
  static readonly TEXT_INPUT_WIDTH: string = '85%';
  /**
   * Empty String.
   */
  static readonly EMPTY_STRING: string = '';
  /**
   * String Zero.
   */
  static readonly STRING_ZERO: string = '0';
  /**
   * IP Address.
   */
  static readonly IP_ADDRESS: string = '127.0.0.1';
  /**
   * Text ID.
   */
  static readonly TEXT_ID: string = 'textId';
  /**
   * Event unsubscription time.
   */
  static readonly EVENT_UNSUBSCRIPTION_TIME: number = 30 * 1000;
  /**
   * Event unsubscription time min.
   */
  static readonly EVENT_UNSUBSCRIPTION_TIME_MIN: number = 10 * 1000;
  /**
   * IP Port.
   */
  static readonly IP_PORT: number = 1234;
  /**
   * Tcp connect timeout.
   */
  static readonly TCP_CONNECT_TIMEOUT: number = 6000;
  /**
   * Text input max length.
   */
  static readonly TEXT_INPUT_MAX_LENGTH: number = 15;
}