/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class CommonConstants {
  /**
   * Height and width is 100%.
   * */
  static readonly FULL_PARENT: string = '100%';
  static readonly START_WINDOW_BACKGROUND: string = "#FFFFFFF";
  static readonly SWIPER_INTERVAL: number = 3500;
  static readonly SWIPER_DURATION: number = 500;
  static readonly SWIPER_ITEM_SPACE: number = 10;
  static readonly HEXADECIMAL: number = 16;
  static readonly ANIMATION_DURATION: number = 500;
  static readonly ANIMATION_ITERATIONS: number = 1;
  static readonly START_GRADIENT_RANGE: number = 0.0;
  static readonly END_GRADIENT_RANGE: number = 0.5;
}