/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

export const SENSOR_PAGE: string = 'pages/SensorPage';

export const SERVICE_PAGE: string = 'pages/ServicePage';

export const P2P_PAGE: string = 'pages/P2pPage';

export const DEVICE_PAGE: string = 'pages/DevicePage';

export const MONITOR_PAGE: string = 'pages/MonitorPage';

export const NOTIFY_PAGE: string = 'pages/NotifyPage';

export const AUTH_PAGE: string = 'pages/AuthPage';

/**
 * Percent for string.
 */
export const enum STRING_PERCENT {
  TEN_PERCENT = '10%',
  FIFTEEN_PERCENT = '15%',
  TWENTY_PERCENT = '20%',
  TWENTY_FIVE_PERCENT = '25%',
  THIRTY_PERCENT = '30%',
  THIRTY_FIVE_PERCENT = '35%',
  FORTY_PERCENT = '40%',
  FORTY_FIVE_PERCENT = '45%',
  FIFTY_PERCENT = '50%',
  FIFTY_FIVE_PERCENT = '55%',
  SIXTY_PERCENT = '60%',
  EIGHTY_PERCENT = '80%',
  NINETY_PERCENT = '90%',
  MAX_PERCENT = '100%'
}

export const enum STRING_MARGIN {
  BUTTON_LEFT_SIZE = '5vp',
  NOTIFY_INPUT_TOP = '5vp',
  PRINT_SCROLL_SIZE = '20vp',
  INPUT_FONT_SIZE = '35vp',
  BUTTON_FONT_SIZE = '15vp',
  TEXT_FONT_SIZE = '14vp',
  TITLE_FONT_SIZE = '16fp',
  TIP_FONT_SIZE = '13fp',
  BUTTONS_TOP_SIZE = '15vp',
  BUTTONS_LEFT_SIZE = '15vp',
  BUTTONS_RIGHT_SIZE = '15vp',
  MARGIN_TOP_SIZE = '15vp',
  TITLE_TIP_LEFT_SIZE = '15vp',
  TITLE_TIP_TOP_SIZE = '10vp',
  TITLE_TIP_RIGHT_SIZE = '15vp',
}