/*
* Copyright (c) 2025 Huawei Device Co., Ltd.
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

export default class CommonConstants {
  /**
   * Height or Width is 100%.
   */
  static readonly FULL_PARENT: string = '100%';
  /**
   * Default Data Value is xxx.
   */
  static readonly DEFAULT_VALUE: string = 'xxx';
  /**
   * AppID title is "AppID".
   */
  static readonly APPID_TITLE: string = 'AppID';
  /**
   * Fingerprint title is "Fingerprint:".
   */
  static readonly FINGERPRINT_TITLE: string = 'Fingerprint';
  /**
   * AppIdentifier title is "AppIdentifier:".
   */
  static readonly APP_IDENTIFIER_TITLE: string = 'AppIdentifier';
  /**
   * Get App Info Page name is GetAppInfo.
   */
  static readonly GET_APP_INFO_PAGE: string = 'GetAppInfo';
  /**
   * Get Signature Info Page name is GetSignatureInfo.
   */
  static readonly GET_SIGNATURE_INFO_PAGE: string = 'GetSignatureInfo';
  /**
   * Native Get AppInfo Page name is NativeGetAppInfo.
   */
  static readonly NATIVE_GET_APP_INFO_PAGE: string = 'NativeGetAppInfo';
}