/*
* Copyright (C) 2024 Huawei Device Co., Ltd.
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

export class CommonConstants {
  /**
   * Size of components.
   */
  static readonly FULL_SIZE: string = '100%';
  static readonly HEIGHT_OR_WIDTH_80: string = '80%';
  static readonly HEIGHT_OR_WIDTH_75: string = '75%';
  static readonly HEIGHT_OR_WIDTH_60: string = '60%';
  static readonly TOP_BAR_HEIGHT: string = '12%';
  static readonly SIGN_UP_TOP_BAR_HEIGHT: string = '20%';
  static readonly LIST_HEIGHT_88: string = '88%';
  static readonly LIST_HEIGHT_76: string = '76%';
  static readonly TEXT_INPUT_WIDTH: string = '87.5%';

  /**
   * String of vp.
   */
  static readonly VP: string = 'vp';

  /**
   * Parameters of components.
   */
  static readonly FONT_WEIGHT_700: number = 700;
  static readonly FONT_WEIGHT_500: number = 500;
  static readonly DURATION: number = 2000;
  static readonly MESSAGE_LENGTH_13: number = 13;
  static readonly MESSAGE_LENGTH_26: number = 26;
  static readonly MESSAGE_LENGTH_39: number = 39;
  static readonly MESSAGE_LENGTH_78: number = 78;
  static readonly FONT_WIDTH: number = 8;
  static readonly PADDING: number = 30;
  static readonly OPACITY: number = 0.6;
  static readonly LAYOUT_WEIGHT: number = 1;
  static readonly ACCOUNT_MAXLENGTH: number = 11;
  static readonly PASSWORD_MAXLENGTH: number = 8;
  static readonly ROW_SPACE: number = 24;

  /**
   * placeholder
   */
  static readonly ACCOUNT_PLACEHOLDER: string = 'Account';
  static readonly PASSWORD_PLACEHOLDER: string = 'Password';

  static readonly EMAIL_ADDRESS: string = 'Email Address';
  static readonly SUBJECT: string = 'Subject';
  static readonly ENTRY_CONTENT: string = 'Entry content';


  static readonly SIGN_UP_SHOW_TOAST: string = 'Account or password can not be null!';
}