/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class CommonConstants {
  /**
   * Full screen.
   */
  static readonly FULL_SCREEN: string = '100%';

  /**
   * 90% screen.
   */
  static readonly NINETY_SCREEN: string = '90%';

  /**
   * 25% screen.
   */
  static readonly TWENTY_FIVE_SCREEN: string = '25%';

  /**
   * GridRow column sm.
   */
  static readonly COLUMN_SM: number = 4;

  /**
   * GridRow column md.
   */
  static readonly COLUMN_MD: number = 8;

  /**
   * GridRow column lg.
   */
  static readonly COLUMN_LG: number = 8;

  /**
   * GridRow span sm.
   */
  static readonly SPAN_SM: number = 8;

  /**
   * GridRow span md.
   */
  static readonly SPAN_MD: number = 4;

  /**
   * GridRow span lg.
   */
  static readonly SPAN_LG: number = 4;

  /**
   * Title font weight.
   */
  static readonly TITLE_FONT_WEIGHT: number = 700;

  /**
   * CurrentIndex.
   */
  static readonly CURRENT_INDEX: number = 3;

  /**
   * GridCol offset sm.
   */
  static readonly OFFSET_SM: number = 8;

  /**
   * GridCol offset md.
   */
  static readonly OFFSET_MD: number = 16;

  /**
   * GridCol offset lg.
   */
  static readonly OFFSET_LG: number = 24;

  /**
   * List title font weight.
   */
  static readonly LIST_TITLE_FONT_WEIGHT: number = 500;

  /**
   * GridRow column sm.
   */
  static readonly LOGIN_COLUMN_SM: number = 4;

  /**
   * GridRow column md.
   */
  static readonly LOGIN_COLUMN_MD: number = 8;

  /**
   * GridRow column sm.
   */
  static readonly LOGIN_COLUMN_LG: number = 12;

  /**
   * GridRow span sm.
   */
  static readonly LOGIN_SPAN_SM: number = 4;

  /**
   * GridRow span md.
   */
  static readonly LOGIN_SPAN_MD: number = 6;

  /**
   * GridRow span lg.
   */
  static readonly LOGIN_SPAN_LG: number = 8;

  /**
   * GridRow offset sm.
   */
  static readonly LOGIN_OFFSET_SM: number = 0;

  /**
   * GridRow offset md.
   */
  static readonly LOGIN_OFFSET_MD: number = 1;

  /**
   * GridRow offset lg.
   */
  static readonly LOGIN_OFFSET_LG: number = 2;

  /**
   * CustomDialogComponentId.
   */
  static readonly CUSTOM_DIALOG_COMPONENT_ID: number = 0;

  /**
   * PromptAction offset X.
   */
  static readonly PROMPT_ACTION_X: number = 0;

  /**
   * PromptAction offset Y.
   */
  static readonly PROMPT_ACTION_Y: number = -20;

  /**
   * PromptAction cornerRadius.
   */
  static readonly CORNER_RADIUS: number = 20;

  /**
   * PromptAction shadow offset X.
   */
  static readonly SHADOW_X: number = 0;

  /**
   * PromptAction shadow offset Y.
   */
  static readonly SHADOW_Y: number = 50;

  /**
   * PromptAction shadow cornerRadius.
   */
  static readonly SHADOW_RADIUS: number = 20;

  /**
   * CustomDialog row space.
   */
  static readonly CUSTOM_DIALOG_ROW_SPACE: number = 4;

  /**
   * CustomDialog row layoutWeight.
   */
  static readonly CUSTOM_DIALOG_ROW_LAYOUT_WEIGHT: number = 1;

  /**
   * MySheet row space.
   */
  static readonly SHEET_ROW_SPACE: number = 16;

  /**
   * TabBuilder column space.
   */
  static readonly TAB_BUILDER_COLUMN_SPACE: number = 6;

  /**
   * GridCol column space.
   */
  static readonly GRID_COLUMN_SPACE: number = 8;

  /**
   * TextInput maxLength.
   */
  static readonly TEXT_INPUT_MAX_LENGTH: number = 24;

  /**
   * Password maxLength.
   */
  static readonly PASSWORD_MAX_LENGTH: number = 12;

  /**
   * Image list.
   */
  static readonly IMAGE_LIST: number[] = [1, 2, 3, 4];

  /**
   * WindowWidthVp SM.
   */
  static readonly WINDOW_WIDTH_VP_SM: number = 320;

  /**
   * WindowWidthVp MD.
   */
  static readonly WINDOW_WIDTH_VP_MD: number = 600;

  /**
   * WindowWidthVp LG.
   */
  static readonly WINDOW_WIDTH_VP_LG: number = 840;
}