/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class CommonConstants {

  /**
   * Height and width is 100%.
   * */
  static readonly FULL_PARENT: string = '100%';

  /**
   * Height and width is 90%.
   * */
  static readonly NINETY_PARENT: string = '90%';

  /**
   * Progress Height and width is 228.
   */
  static readonly PROGRESS_SIZE: number = 228;

  /**
   * progress length is 100.
   */
  static readonly PROGRESS_LENGTH: number = 100;

  /**
   * Layout weight is 1.
   */
  static readonly LAYOUT_WEIGHT: number = 1;

  /**
   * Font weight is 400.
   */
  static readonly FONT_WEIGHT: number = 400;

  /**
   * PROGRESS ANIMATION DURATION is 1000.
   */
  static readonly PROGRESS_ANIMATION_DURATION: number = 1000;

  static readonly PROGRESS_START: number = 0;;

  static readonly START_DOWNLOAD: string = 'Start Download';

  static readonly DOWNING: string = 'Downloading';
}