/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class LiveConstants {
  /**
   * Capsule background color.
   */
  static readonly CAPSULE_COLOR: string = '#FF0A59F7';

  /**
   * Capsule icon.
   */
  static readonly CAPSULE_ICON: string = 'navigate.png';

  /**
   * Live view title.
   */
  static readonly LIVE_VIEW_TITLE: string = '司机已接单';

  /**
   * Live view content.
   */
  static readonly LIVE_VIEW_CONTENT: string = '距离你 ';

  /**
   * Live view distance.
   */
  static readonly LIVE_VIEW_DISTANCE: string = '1公里';

  /**
   * Live view distance color.
   */
  static readonly LIVE_VIEW_DISTANCE_COLOR: string = '#FF0A59F7';

  /**
   * Taxi infomation.
   */
  static readonly TAXI_BRAND_INFO: string = '深空灰·问界M7';

  /**
   * Taxi time infomation.
   */
  static readonly TAXI_LICENCE_INFO: string = '牌123456';

  /**
   * Taxi icon.
   */
  static readonly TAXI_ICON: string = 'taxi.png';

  /**
   * UnderLine color.
   */
  static readonly UNDERLINE_COLOR: string = '#00ffffff';

  /**
   * Capsule keep time.
   */
  static readonly TIME: number = 15;

  /**
   * Bundle name.
   */
  static readonly BUNDLE_NAME: string = 'com.example.multitravelnavigation';

  /**
   * Ability name.
   */
  static readonly ABILITY_NAME: string = 'EntryAbility';
}