/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class ConstValues {
  /**
   * How much money.
   */
  static readonly MONEY: string = '88888.88';
  /**
   * The benefits.
   */
  static readonly BENEFIT: string = '+3.63';
  /**
   * Flexible access name
   */
  static readonly FLEXIBLE_ACCESS: ResourceStr = $r('app.string.flexible_access');
  /**
   * Stable financial management
   */
  static readonly STABLE_FINANCIAL_MANAGEMENT: ResourceStr = $r('app.string.stable_financial_management');
  /**
   * Advanced Financial Management
   */
  static readonly ADVANCED_FINANCIAL_MANAGEMENT: ResourceStr = $r('app.string.advanced_financial_management');
  /**
   * Default money.
   */
  static readonly DEFAULT_MONEY: string = '0.00';
  /**
   * The benefits.
   */
  static readonly DEFAULT_BENEFIT: string = '0.00';
  /**
   * default hide info
   */
  static readonly DEFAULT_HIDE_INFO: string = '****';
}